
server:
  port: 7071

spring:
  application:
    name: Department-Setup

  datasource:
    url: jdbc:mysql://localhost:3306/database_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

